### ISSUE TITLE
A short todo list

### ISSUE THREAD

**Issue by milasudril** [milasudril/happychords#1]
Some remaining stuff
 - [ ] Add support for different patterns + Random button
 - [ ] Blinking stars synced with beat?
 - [ ] Make the UI an external process using standard input/output
